apiVersion: v1
kind: Service
metadata:
  name: compulysis-db-service
  labels:
    app: compulysis-db
spec:
  type: NodePort
  selector:
    app: compulysis-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30054
